baseurl = "/website"
languageCode = "en-us"
title = "UMD Microbiome Journal Club"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
publishDir = "docs"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Meetings"
    url = "/meetings/"
    weight = 2
[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 3
[[menu.main]]
    name = "People"
    url = "/people/"
    weight = 4
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 5
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 6
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "THE UMD Mirobiome Journal Club website"
    footer = "&copy; Dan Nasko 2017 | [Github](https://github.com/dnasko) | [Twitter](https://twitter.com/dnasko)"
